"""add story analytics events

Revision ID: acbab0da5249
Revises: e4a006ea05c8
Create Date: 2026-09-29 01:00:48.186867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acbab0da5249'
down_revision = 'e4a006ea05c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('kalxa_restaurant_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_analytics_events_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_analytics_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_analytics_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_analytics_events_kalxa_restaurant_id'), ['kalxa_restaurant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_analytics_events_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_analytics_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_story_analytics_events_kalxa_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_story_analytics_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_story_analytics_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_story_analytics_events_article_id'))

    op.drop_table('story_analytics_events')
    # ### end Alembic commands ###
