from datetime import datetime, timezone

from app.extensions import db


# ============================================================
# RESTAURANT ANALYTICS EVENT
# ============================================================

class RestaurantAnalyticsEvent(db.Model):

    __tablename__ = "restaurant_analytics_events"


    # ========================================================
    # PRIMARY KEY
    # ========================================================

    id = db.Column(
        db.Integer,
        primary_key=True,
    )


    # ========================================================
    # KALXA TICKETING RESTAURANT
    # ========================================================
    #
    # IMPORTANT:
    #
    # This is an EXTERNAL Kalxa Ticketing restaurant ID.
    #
    # It is deliberately NOT a database foreign key.
    #
    # Kalxa Stories and Kalxa Ticketing are separate
    # applications with separate databases.
    #
    # Example:
    #
    # restaurant_advert_id = 12
    #
    # means RestaurantAdvert #12 inside Kalxa Ticketing.
    #
    # Kalxa Stories stores the ID only for attribution.
    # ========================================================

    restaurant_advert_id = db.Column(
        db.Integer,
        nullable=False,
        index=True,
    )


    # ========================================================
    # EVENT
    # ========================================================
    #
    # Examples:
    #
    # restaurant_view
    # whatsapp_click
    # directions_click
    # experience_view
    # booking_click
    # menu_view
    # ========================================================

    event_type = db.Column(
        db.String(50),
        nullable=False,
        index=True,
    )


    # ========================================================
    # OPTIONAL EXPERIENCE
    # ========================================================
    #
    # External Kalxa Ticketing experience post ID.
    #
    # This is also deliberately NOT a database foreign key
    # inside Kalxa Stories.
    # ========================================================

    experience_post_id = db.Column(
        db.Integer,
        nullable=True,
        index=True,
    )


    # ========================================================
    # ATTRIBUTION SOURCE
    # ========================================================
    #
    # Examples:
    #
    # kalxa_stories
    # direct
    # qr
    # kalxa_discovery
    #
    # ========================================================

    source = db.Column(
        db.String(50),
        nullable=False,
        default="direct",
        index=True,
    )


    # ========================================================
    # KALXA STORIES ATTRIBUTION
    # ========================================================
    #
    # Stores the Article.id from Kalxa Stories when a
    # restaurant interaction originated from a story.
    #
    # We intentionally keep this as a plain integer.
    #
    # This makes the attribution payload portable between
    # Kalxa Stories and Kalxa Ticketing.
    # ========================================================

    source_story_id = db.Column(
        db.Integer,
        nullable=True,
        index=True,
    )


    # ========================================================
    # ANONYMOUS ATTRIBUTION SESSION
    # ========================================================
    #
    # Anonymous session generated by Kalxa Stories.
    #
    # This lets us measure:
    #
    # Story
    #   ↓
    # Restaurant
    #   ↓
    # WhatsApp / Directions / Experience
    #
    # without requiring the visitor's name, phone number
    # or email address.
    # ========================================================

    source_session_id = db.Column(
        db.String(100),
        nullable=True,
        index=True,
    )


    # ========================================================
    # TICKETING SESSION
    # ========================================================
    #
    # Optional anonymous session identifier generated on
    # the Kalxa Ticketing side.
    # ========================================================

    session_id = db.Column(
        db.String(100),
        nullable=True,
        index=True,
    )


    # ========================================================
    # OPTIONAL EVENT METADATA
    # ========================================================
    #
    # Examples:
    #
    # {
    #     "source": "story_restaurant_card"
    # }
    #
    # {
    #     "position": 1
    # }
    #
    # {
    #     "action": "whatsapp"
    # }
    # ========================================================

    event_metadata = db.Column(
        db.JSON,
        nullable=True,
    )


    # ========================================================
    # CREATED
    # ========================================================

    created_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(
            timezone.utc
        ),
        index=True,
    )


    # ========================================================
    # IMPORTANT DATABASE ARCHITECTURE NOTE
    # ========================================================
    #
    # There is deliberately NO relationship such as:
    #
    # restaurant = db.relationship("RestaurantAdvert")
    #
    # RestaurantAdvert belongs to Kalxa Ticketing and does
    # not exist inside the Kalxa Stories SQLAlchemy metadata.
    #
    # Restaurant information must be resolved through the
    # Kalxa Ticketing API using restaurant_advert_id.
    # ========================================================


    # ========================================================
    # REPRESENTATION
    # ========================================================

    def __repr__(self):

        return (
            "<RestaurantAnalyticsEvent "
            f"id={self.id} "
            f"restaurant={self.restaurant_advert_id} "
            f"event={self.event_type} "
            f"source={self.source}>"
        )
